#!/bin/bash

cd
mkdir -p ~/atomic/$1
cd ~/atomic/$1

declare -A urls=( ["docker"]="https://raw.githubusercontent.com/projectatomic/adb-atomic-developer-bundle/master/components/centos/centos-docker-base-setup/Vagrantfile" ["kubernetes"]="https://raw.githubusercontent.com/projectatomic/adb-atomic-developer-bundle/master/components/centos/centos-k8s-singlenode-setup/Vagrantfile" ["openshift"]="https://raw.githubusercontent.com/projectatomic/adb-atomic-developer-bundle/master/components/centos/centos-openshift-setup/Vagrantfile")

curl -O ${urls[$2]}
git clone https://gist.github.com/a544d8b2d97ca3cd6583.git
vagrant up
